from __future__ import annotations
import io
from datetime import datetime
from typing import Any, Dict, List

# NOTE: extracted from legacy.py
from docmate.core.recalc import _recalc_items, _safe_float

APP_VERSION = "v1.07.001_r06"
APP_DATE = "2026-02-10"


def _footer(canvas, doc_obj) -> None:
    """Legacy-compatible footer callback export."""
    try:
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.drawString(34, 20, "Generated by DocMate (Visual Business Retail Ltd).")
        canvas.drawRightString(800, 20, f"Page {getattr(doc_obj, 'page', '')}")
        canvas.restoreState()
    except Exception:
        pass

def _calc_vat_breakdown_from_items(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Group calculated VAT breakdown from line items."""
    by_code: Dict[str, Dict[str, float]] = {}
    for it in (items or []):
        code = str(it.get("vatCode") or "").strip().upper() or "UNK"
        net = _safe_float(it.get("lineNet"))
        vat = _safe_float(it.get("vatAmount"))
        gross = _safe_float(it.get("lineGross"))
        # Avoid polluting the breakdown with an empty UNK row (common after manual edits)
        if code == "UNK" and net == 0.0 and vat == 0.0 and gross == 0.0:
            continue
        if (gross == 0 and net != 0) or (abs(gross - net) < 0.01 and abs(vat) > 0.01):
            gross = net + vat
        if code not in by_code:
            by_code[code] = {"net": 0.0, "vat": 0.0, "gross": 0.0}
        by_code[code]["net"] += net
        by_code[code]["vat"] += vat
        by_code[code]["gross"] += gross

    rows: List[Dict[str, Any]] = []
    for code, agg in by_code.items():
        rows.append(
            {
                "vatCode": code,
                "netAmount": round(agg["net"], 2),
                "vatAmount": round(agg["vat"], 2),
                "grossAmount": round(agg["gross"], 2),
                "_source": "calculated",
            }
        )
    return rows
def _generate_pdf_report_bytes(
    file_name: str,
    header: Dict[str, Any],
    items: List[Dict[str, Any]],
    reconciliation: Dict[str, Any],
    recon_notes: List[str],
) -> bytes:
    """
    Generate a printable PDF report (A4 landscape) for the processed invoice.

    IMPORTANT:
    - Requires 'reportlab' to be installed on the runtime machine.
    - If reportlab is missing, we raise a clear error so the UI can show guidance
      (and fall back to HTML report download).
    """
    try:
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib import colors
        from reportlab.lib.units import mm
    except Exception as e:
        raise RuntimeError("PDF engine not available. Please install 'reportlab' (pip install reportlab).") from e

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=landscape(A4),
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=10 * mm,
        bottomMargin=10 * mm,
        title="DocMate Invoice Audit Report",
        author="Visual Business Retail Ltd",
    )

    styles = getSampleStyleSheet()
    story: List[Any] = []

    from reportlab.lib.enums import TA_CENTER
    # Report heading
    release_date_disp = APP_DATE
    try:
        release_date_disp = datetime.strptime(str(APP_DATE), "%Y-%m-%d").strftime("%d/%m/%Y")
    except Exception:
        pass

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    small_style = styles["BodyText"]
    small_style.alignment = TA_CENTER

    story.append(Paragraph("<b>DocMate Invoice Audit Report</b>", title_style))
    story.append(Paragraph(f"<b>Version:</b> {APP_VERSION} | <b>Release Date:</b> {release_date_disp}", small_style))
    story.append(Spacer(1, 6))

    supplier = str(header.get("supplierName") or "")
    story.append(Paragraph(f"DocMate Invoice Report for Supplier: <b>{supplier}</b> - Doc. File Name: <b>{file_name}</b>", styles["BodyText"]))
    story.append(Spacer(1, 8))

    customer = str(header.get("customerName") or "")
    inv_no = str(header.get("invoiceNumber") or "")
    inv_date = str(header.get("invoiceDate") or "")
    # Keep date only (strip any time component)
    if " " in inv_date:
        inv_date = inv_date.split(" ")[0]
    if "T" in inv_date:
        inv_date = inv_date.split("T")[0]

    # Totals: captured header vs calculated from items (after any edits)
    calc_items = _recalc_items(items)
    net_calc = round(sum(_safe_float(i.get("lineNet")) for i in calc_items), 2)
    vat_calc = round(sum(_safe_float(i.get("vatAmount")) for i in calc_items), 2)
    gross_calc = round(sum(_safe_float(i.get("lineGross")) for i in calc_items), 2)

    net_hdr = round(_safe_float(header.get("totalNet")), 2)
    vat_hdr = round(_safe_float(header.get("totalVat")), 2)
    gross_hdr = round(_safe_float(header.get("totalGross")), 2)

    summary_data = [
        ["Supplier", supplier, "Customer", customer],
        ["Invoice Date", inv_date, "Invoice Number", inv_no],
        ["Header Net", f"{net_hdr:,.2f}", "Line Net", f"{net_calc:,.2f}"],
        ["Header VAT", f"{vat_hdr:,.2f}", "Line VAT", f"{vat_calc:,.2f}"],
        ["Header Gross", f"{gross_hdr:,.2f}", "Line Gross", f"{gross_calc:,.2f}"],
    ]
    t = Table(summary_data, colWidths=[28*mm, 70*mm, 28*mm, 70*mm])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 2), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    story.append(t)
    story.append(Spacer(1, 8))

    # Reconciliation
    story.append(Paragraph("<b>Reconciliation</b>", styles["Heading2"]))
    recon_rows = [
        ["Check", "Line Items", "Header", "Diff", "Status"],
        ["Net", f"{net_calc:,.2f}", f"{net_hdr:,.2f}", f"{(net_calc-net_hdr):,.2f}", str(reconciliation.get("netStatus") or "")],
        ["VAT", f"{vat_calc:,.2f}", f"{vat_hdr:,.2f}", f"{(vat_calc-vat_hdr):,.2f}", str(reconciliation.get("vatStatus") or "")],
        ["Gross", f"{gross_calc:,.2f}", f"{gross_hdr:,.2f}", f"{(gross_calc-gross_hdr):,.2f}", str(reconciliation.get("grossStatus") or "")],
    ]
    rt = Table(recon_rows, colWidths=[18*mm, 28*mm, 28*mm, 22*mm, 20*mm])
    rt.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    story.append(rt)

    if recon_notes:
        story.append(Spacer(1, 6))
        notes_txt = "<br/>".join([f"- {str(n)}" for n in recon_notes])
        story.append(Paragraph(f"<b>Notes</b><br/>{notes_txt}", styles["BodyText"]))

    story.append(Spacer(1, 10))

    # VAT Breakdown (calculated)
    story.append(Paragraph("<b>VAT Breakdown (calculated from line items)</b>", styles["Heading2"]))
    vat_rows = _calc_vat_breakdown_from_items(calc_items)
    vat_table = [["VAT Code", "Net", "VAT", "Gross"]]
    for r in vat_rows:
        vat_table.append([
            str(r.get("vatCode") or ""),
            f'{_safe_float(r.get("netAmount")):,.2f}',
            f'{_safe_float(r.get("vatAmount")):,.2f}',
            f'{_safe_float(r.get("grossAmount")):,.2f}',
        ])
    vt = Table(vat_table, colWidths=[24*mm, 26*mm, 26*mm, 26*mm])
    vt.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    story.append(vt)
    story.append(Spacer(1, 10))

    # Line items table (truncate description for PDF width)
    story.append(Paragraph("<b>Line Items</b>", styles["Heading2"]))
    cols = ["lineNo","code","description","casePack","unitSize","qty","totalUnits","unitPrice","lineNet","vatCode","vatRate","vatAmount","lineGross"]
    table_rows = [cols]
    for it in calc_items:
        desc = str(it.get("description") or "")
        if len(desc) > 60:
            desc = desc[:57] + "..."
        row = [
            str(it.get("lineNo") or ""),
            str(it.get("code") or ""),
            desc,
            str(it.get("casePack") or ""),
            str(it.get("unitSize") or ""),
            f'{_safe_float(it.get("qty")):g}',
            f'{_safe_float(it.get("totalUnits")):g}',
            f'{_safe_float(it.get("unitPrice")):,.2f}',
            f'{_safe_float(it.get("lineNet")):,.2f}',
            str(it.get("vatCode") or ""),
            f'{_safe_float(it.get("vatRate")):g}',
            f'{_safe_float(it.get("vatAmount")):,.2f}',
            f'{_safe_float(it.get("lineGross")):,.2f}',
        ]
        table_rows.append(row)


    # Totals row (calculated fields)
    tot_qty = round(sum(_safe_float(i.get("qty")) for i in calc_items), 3)
    tot_units = round(sum(_safe_float(i.get("totalUnits")) for i in calc_items), 3)
    tot_net = round(sum(_safe_float(i.get("lineNet")) for i in calc_items), 2)
    tot_vat = round(sum(_safe_float(i.get("vatAmount")) for i in calc_items), 2)
    tot_gross = round(sum(_safe_float(i.get("lineGross")) for i in calc_items), 2)

    total_row = ["", "", "TOTAL", "", "", f"{tot_qty:g}", f"{tot_units:g}", "", f"{tot_net:,.2f}", "", "", f"{tot_vat:,.2f}", f"{tot_gross:,.2f}"]
    table_rows.append(total_row)

    lt = Table(table_rows, repeatRows=1)
    lt.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, -1), (-1, -1), colors.whitesmoke),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("LINEABOVE", (0, -1), (-1, -1), 0.6, colors.black),
            ]
        )
    )
    story.append(lt)

    # Footer
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)

    pdf_bytes = buf.getvalue()
    # Guard: never allow empty/near-empty PDF to be downloaded
    if not pdf_bytes or len(pdf_bytes) < 500:
        raise RuntimeError("PDF generation produced empty output.")
    return pdf_bytes
